baseURL: https://ronapat-portfolio.netlify.app/
languageCode: en-us
title: Ronapat Srisupavanich
theme: Forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: This is Ronapat's personal website.
    title: Hi, my name is Ronapat!
  blog: {}
  contact:
    address:
      - city: London, United Kingdom | Bangkok, Thailand
        country:
        street:
        title: Location
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rons.mba2023@london.edu | ronapat@hotmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 70-4232-6459
        title: Phone
  custom_css: []
  custom_js: []
  description: #Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ronapat Srisupavanich
    enable: yes
    quicklinks:
      # - alt: HTML5 UP
      #   text: 'Design: '
      #   url: #https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/Ron_Pound
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/ronapat
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/ron_pound
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/ronapats
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ronapat
  image: ''
  name: Ronapat Srisupavanich
  navigation:
    # button1:
    #   - name: Get Started
    #     url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs
      - name: Travel Blogs
        url: blogs/ipsum
      - name: Books
        url: blogs/ipsum
      - name: Projects
        url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    # subtitle: By HTML5 Up
    # title: Forty
  tiles:
    enable: yes
    showcase:
      - image: LBS-profile.jpg
        subtitle: :)
        title: About Me
        url: blogs/risk_return
      - image: Bromo.jpg
        subtitle: Places I've visited :)
        title: Travel Blogs
        url: blogs/tempus
      - image: books.jpg
        subtitle: Summary of books that I've read in Y2023
        title: Books
        url: blogs/magna
      - image: project.jpg
        subtitle: Data Science with R
        title: Projects
        url: blogs/ipsum
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Consequat
      #   url: blogs/ipsum
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/ipsum
  # two:
    # buttonText: Get Started
    # enable: yes
    # subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    #   \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
    #   condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
    #   pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
    #   Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
    #   amet pharetra et feugiat tempus."
    # title: Massa libero
    # url: blogs
